# Generated by Django 2.1.1 on 2018-09-08 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anc',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(verbose_name='Date entered')),
            ],
        ),
        migrations.CreateModel(
            name='Commissioner',
            fields=[
                ('commissioner_name', models.CharField(help_text='First and last name of the commissioner of this ANC', max_length=20, primary_key=True, serialize=False)),
                ('active', models.BooleanField(verbose_name='Active status of commissioner')),
                ('anc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancfinder_site.Anc')),
            ],
        ),
        migrations.CreateModel(
            name='Smd',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(verbose_name='Date entered')),
                ('anc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancfinder_site.Anc')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(verbose_name='Date entered')),
            ],
        ),
        migrations.AddField(
            model_name='anc',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancfinder_site.Ward'),
        ),
    ]
