# Generated by Django 2.1.2 on 2018-10-07 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ancfinder_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anc',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date entered'),
        ),
        migrations.AlterField(
            model_name='smd',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date entered'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date entered'),
        ),
    ]
