# Generated by Django 2.1.2 on 2018-10-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancfinder_site', '0002_auto_20181007_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='anc',
            name='boundries',
            field=models.TextField(default='', verbose_name='Boundry of the Anc'),
            preserve_default=False,
        ),
    ]
